var page = 0;
var startTime = new Date().toUTCString();
var id = Math.floor(Math.random() * 10000);
var admin, db, surveyResponse, ref = null;

var dbStructure = {
  overview:[],
  entries:[]
};

function startDB()
{
  // Get a database reference to our blog
  db = firebase.database();

  // Get a new reference:
  refEntry = db.ref('survey-data-' + config.env + '/entries/entry-' + id);
  refOverviewParticipantsCount = db.ref('survey-data-' + config.env + '/overview/participant-count');
}

function updateEntries(sendObject){
  var updates = {};

  refEntry.update(sendObject) 
}

function nextPage()
{
  var sendOverview = {};
  var countParticipants;
  var currentPage = document.getElementById("page"+page);

  document.querySelectorAll('.page').forEach(function(pageElement) {
    pageElement.style.display = "none";
  });

  document.getElementById("page" + page).style.display = "block";

  if (page == 1){
    refOverviewParticipantsCount.transaction(function(countParticipants) {
      if (countParticipants == null) {
        return 1;
      } else {
        return countParticipants + 1;
      }
    })
  }

  if (page > 0){
    collectAndSendInputs()
  }

  page++

  var randomImages = $('#page'+page+' .random');

  for(var i = 0; i < randomImages.length; i++){
      var target = Math.floor(Math.random() * randomImages.length -1) + 1;
      var target2 = Math.floor(Math.random() * randomImages.length -1) +1;
      randomImages.eq(target).before(randomImages.eq(target2));
  }
}

// function visualTransition(){
//   var accent = document.querySelectorAll(".accent")

//   accent[0].style.background-color = "black";
// }

function collectAndSendInputs() {
  var questions = document.querySelectorAll(".question")
  var answerPath = 'results/question-'
  var sendObject = {}

  //Basic
  sendObject["id"] = id
  sendObject["startTime"] = startTime
  sendObject["completeTime"] = new Date().toUTCString();

  //Questions
  for (var i = 0; i < questions.length; i++){

    sendObject[answerPath + (i+1) + '/id'] = questions[i].id;
    if (questions[i].id % 2 == 0){

      sendObject[answerPath + (i+1) + '/type'] = "Generated by AI";
    }else{

      sendObject[answerPath + (i+1) + '/type'] = "By Humans";
    }

    var inputs = questions[i].querySelectorAll("input")
    var result = "no answer";

    for (var j = 0; j < inputs.length; j++){
      if (inputs[j].type == "radio"){

        sendObject[answerPath + (i+1) + '/' + inputs[j].value] = inputs[j].checked

        if (inputs[j].checked){
          if (inputs[j].value == "selects-ai" && questions[i].id % 2 == 0){
            result = "correct";
          } else if (inputs[j].value == "selects-human" && Math.abs(questions[i].id % 2) == 1){
            result = "correct";
          } else {
            result = "wrong";
          }
        }
      }
    }

    sendObject[answerPath + (i+1) + '/result'] = result;
  }

  updateEntries(sendObject);
}

function start()
{
  startDB();
  nextPage();
}